apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      host: clickhouse
      port: 9000
      defaultDatabase: livepeer_analytics
      defaultTable: ai_stream_status
      protocol: native
      secure: false
      username: analytics_user
    secureJsonData:
      password: analytics_password
    isDefault: true
    editable: true
