apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:9000
    jsonData:
      defaultDatabase: livepeer_analytics
      defaultTable: ai_stream_status
      protocol: native
      secure: false
      username: analytics_user
    secureJsonData:
      password: analytics_password
    isDefault: true
    editable: true
